- project:
    check:
      jobs:
        - openstack-tox-lower-constraints
        - legacy-pbr-installation-dsvm
        - legacy-pbr-installation-dsvm-upstream
    gate:
      jobs:
        - openstack-tox-lower-constraints
        - legacy-pbr-installation-dsvm
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - lib-forward-testing
      - lib-forward-testing-python3
      - openstack-pypy-jobs-nonvoting
      - publish-openstack-docs-pti
      - periodic-stable-jobs
      - openstack-python36-jobs
    post:
      jobs:
        - openstack-tox-cover
